services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: gharbazaar-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: gharbazaar
    restart: always
  mailpit:
    image: axllent/mailpit
    container_name: mail-server
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always
#  redis:
#    image: redis:latest
#    container_name: gharbazaar-redis
#    ports:
#      - "6379:6379"
#    restart: always